version: 0.0
os: windows
files:
  - source: \index.html
    destination: c:\inetpub\wwwroot
hooks:
  ApplicationStop:
    - location: \before-install.bat
      timeout: 34
  DownloadBundle:
    - location: \before-install.bat
      timeout: 34      
  BeforeInstall:
    - location: \before-install.bat
      timeout: 35
  Install:
    - location: \before-install.bat
      timeout: 35
  AfterInstall:
    - location: \before-install.bat
      timeout: 35
  ApplicationStart:
    - location: \before-install.bat
      timeout: 35  
  ValidateService:
    - location: \before-install.bat
      timeout: 35       
